### ISSUE TITLE
AutoGeo

### ISSUE THREAD

**Issue by bjggi** [PeachBlossomWine/GearSwap#2]
Hey there

Thanks for keeping Sel.GS updated!

A Question about AutoGeo, i tried it about 2 Months ago, but i hat some trouble and i went back to CurePlease. But i kinda really would like to switch to GS controlled Geo, so i could use commands to switch spells. 

Now the Problem i had was the following, a lot of times the Geo was placing the Bubble right when i pulled something on my RDM with Dia from further away, and the Bubble was way off. Another Problem, when doing Alliance stuff, even when someone is aggroing or pulling something my GEO stats bubbling. 

Is there a way to prevent this. Maybe like CurePlease where it monitors only my Main Char. And only if he is engaging, it places the bubble?

Best regards

**Comment by PeachBlossomWine** [comment]
The most latest of GearSwap update should do this already, I just recently modified so any JA like BOG/EA or even Bolster if zergmode is activated won't start until the mob is in range, even if someone pulled it already.  Also the bubble placement will remove bubble if it's not close enough to a <bt>, if there are multiple then it's based off what the game considers current <bt>

**Comment by bjggi** [comment]
Ah ur right, will gladly test this in the next days. 👍

I wonder if something like this could also be used for certain "autobuff" JA, for example War. Often im still in combat but far away, like sleeping Mobs in Sortie, warping to another Basement, and my war keeps doing Berserk/Aggressor etc. :)
